# Generated by Django 3.0.7 on 2020-08-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
